import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

export default defineConfig({
  main: {
    plugins: [
      externalizeDepsPlugin({
        exclude: [
          'pdfkit',
          'fontkit',
          'deep-equal',
          'object.assign',
          'call-bind',
          'call-bound',
          'set-function-length',
          'get-intrinsic',
          'get-proto',
          'dunder-proto',
          'call-bind-apply-helpers',
          'es-define-property',
          'es-errors',
          'es-object-atoms',
          'gopd',
          'has-symbols',
          'has-property-descriptors',
          'has-proto',
          'hasown',
          'function-bind',
          'math-intrinsics',
          'array-buffer-byte-length',
          'available-typed-arrays',
          'is-arguments',
          'is-array-buffer',
          'is-date-object',
          'is-regex',
          'is-shared-array-buffer',
          'is-typed-array',
          'object-is',
          'object-keys',
          'regexp.prototype.flags',
          'side-channel',
          'side-channel-list',
          'side-channel-map',
          'side-channel-weakmap',
          'which-boxed-primitive',
          'which-collection',
          'which-typed-array',
          'define-data-property',
          'define-properties',
          'for-each',
          'functions-have-names',
          'set-function-name',
          'is-bigint',
          'is-boolean-object',
          'is-callable',
          'is-finalizationregistry',
          'is-generator-function',
          'is-map',
          'is-number-object',
          'is-set',
          'is-string',
          'is-symbol',
          'is-weakmap',
          'is-weakset',
          'stop-iteration-iterator',
          'es-get-iterator',
          'isarray',
          'pako',
          'restructure',
          'unicode-properties',
          'unicode-trie',
          'tiny-inflate',
          'brotli',
          'png-js',
          'linebreak',
          'dfa',
          'clone',
          'crypto-js',
          'jpeg-exif',
          'browserify-zlib',
          'pako',
          'base64-js',
          'safe-buffer',
        ],
      }),
    ],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts'),
        },
        output: {
          format: 'cjs',
        },
      },
    },
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/preload/index.ts'),
        },
      },
    },
  },
  renderer: {
    root: resolve(__dirname, 'src/renderer'),
    plugins: [react()],
    resolve: {
      alias: {
        '@': resolve(__dirname, 'src/renderer'),
        '@shared': resolve(__dirname, 'src/shared'),
      },
    },
    build: {
      rollupOptions: {
        input: resolve(__dirname, 'src/renderer/index.html'),
      },
    },
  },
})
